platform :ios, '9.0'
target 'BOHAN-Custom' do
pod 'AFNetworking','~> 3.1.0'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'SAMKeychain'
#pod 'SocketRocket'
pod 'Masonry', '1.0.2'
pod 'Realm'
pod 'MJRefresh'
end
